version: '3'
services:
  # https://www.digitalocean.com/community/tutorials/how-to-set-up-laravel-nginx-and-mysql-with-docker-compose
  #PHP Service
  app:
    image: guoxiangke/x-resource
    links:
      - db:mysql
      - redis
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: unless-stopped
    ports:
      - "8008:80"
    environment:
      CONTAINER_ROLE: app
      REDIS_PORT: 6379
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./:/var/www/html

  #MySQL Service
  db:
    image: mysql:latest
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - /tmp:/sql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:latest
    restart: always

volumes:
  db_data:
